Fix simplecov error by not requiring gems
I encountered the following when trying to run `bin/rails test:all` locally.

```
/Users/j.julio/.rbenv/versions/3.4.5/lib/ruby/gems/3.4.0/gems/simplecov-0.22.0/lib/minitest/simplecov_plugin.rb:8:in 'Minitest.plugin_simplecov_init': undefined method 'external_at_exit=' for module SimpleCov (NoMethodError)

      SimpleCov.external_at_exit = true
               ^^^^^^^^^^^^^^^^^^^
	from /Users/j.julio/.rbenv/versions/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:132:in 'block in Minitest.init_plugins'
	from /Users/j.julio/.rbenv/versions/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:126:in 'Array#each'
	from /Users/j.julio/.rbenv/versions/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:126:in 'Minitest.init_plugins'
	from /Users/j.julio/.rbenv/versions/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:282:in 'Minitest.run'
	from /Users/j.julio/.rbenv/versions/3.4.5/lib/ruby/gems/3.4.0/gems/minitest-5.25.5/lib/minitest.rb:86:in 'block in Minitest.autorun'
```

I believe the cause may have been a recent change simplecov-cobertura. We don't require simplecov unless the COVERAGE environment variable is set. By not requiring that gem too, the error goes away.